<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
        <LangVersion>latestmajor</LangVersion>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="**\*.shared.cs"/>
        <Compile Include="Android\Extensions\CornerPointsExtensions.cs" />
        <Compile Include="Android\Extensions\RectFExtensions.cs" />
    </ItemGroup>
    <ItemGroup Condition="$(TargetFramework.EndsWith('android'))">
        <Compile Include="**\*.android.cs"/>
        <PackageReference Include="Xamarin.AndroidX.Camera.Camera2" Version="1.5.3.1" />
        <PackageReference Include="Xamarin.AndroidX.Camera.View" Version="1.5.3.1" />
        <PackageReference Include="Xamarin.AndroidX.ConstraintLayout" Version="2.2.1.5" />
        <PackageReference Include="Xamarin.Google.MLKit.BarcodeScanning" Version="117.3.0.7" />
        <AndroidResource Include="Resources\layout\*.xml"/>
    </ItemGroup>
    <ItemGroup Condition="$(TargetFramework.EndsWith('ios'))">
        <Compile Include="**\*.ios.cs"/>
    </ItemGroup>
</Project>
